/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DialectRouteImport } from './routes/dialect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'
import { Route as LessonsIdIndexRouteImport } from './routes/lessons.$id.index'
import { Route as LessonsIdQuizRouteImport } from './routes/lessons.$id.quiz'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DialectRoute = DialectRouteImport.update({
  id: '/dialect',
  path: '/dialect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdIndexRoute = LessonsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonsIdRoute,
} as any)
const LessonsIdQuizRoute = LessonsIdQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => LessonsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dialect': typeof DialectRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/lessons/$id': typeof LessonsIdRouteWithChildren
  '/lessons/$id/quiz': typeof LessonsIdQuizRoute
  '/lessons/$id/': typeof LessonsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dialect': typeof DialectRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/lessons/$id/quiz': typeof LessonsIdQuizRoute
  '/lessons/$id': typeof LessonsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dialect': typeof DialectRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/lessons/$id': typeof LessonsIdRouteWithChildren
  '/lessons/$id/quiz': typeof LessonsIdQuizRoute
  '/lessons/$id/': typeof LessonsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dialect'
    | '/profile'
    | '/settings'
    | '/lessons/$id'
    | '/lessons/$id/quiz'
    | '/lessons/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dialect'
    | '/profile'
    | '/settings'
    | '/lessons/$id/quiz'
    | '/lessons/$id'
  id:
    | '__root__'
    | '/'
    | '/dialect'
    | '/profile'
    | '/settings'
    | '/lessons/$id'
    | '/lessons/$id/quiz'
    | '/lessons/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DialectRoute: typeof DialectRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  LessonsIdRoute: typeof LessonsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialect': {
      id: '/dialect'
      path: '/dialect'
      fullPath: '/dialect'
      preLoaderRoute: typeof DialectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id/': {
      id: '/lessons/$id/'
      path: '/'
      fullPath: '/lessons/$id/'
      preLoaderRoute: typeof LessonsIdIndexRouteImport
      parentRoute: typeof LessonsIdRoute
    }
    '/lessons/$id/quiz': {
      id: '/lessons/$id/quiz'
      path: '/quiz'
      fullPath: '/lessons/$id/quiz'
      preLoaderRoute: typeof LessonsIdQuizRouteImport
      parentRoute: typeof LessonsIdRoute
    }
  }
}

interface LessonsIdRouteChildren {
  LessonsIdQuizRoute: typeof LessonsIdQuizRoute
  LessonsIdIndexRoute: typeof LessonsIdIndexRoute
}

const LessonsIdRouteChildren: LessonsIdRouteChildren = {
  LessonsIdQuizRoute: LessonsIdQuizRoute,
  LessonsIdIndexRoute: LessonsIdIndexRoute,
}

const LessonsIdRouteWithChildren = LessonsIdRoute._addFileChildren(
  LessonsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DialectRoute: DialectRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  LessonsIdRoute: LessonsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
