/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PhrasebookRouteImport } from './routes/phrasebook'
import { Route as HobbiesRouteImport } from './routes/hobbies'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as HobbiesIndexRouteImport } from './routes/hobbies/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileProgressRouteImport } from './routes/profile/progress'
import { Route as LessonsLevelRouteImport } from './routes/lessons/$level'
import { Route as HobbiesHobbySlugRouteImport } from './routes/hobbies/$hobbySlug'
import { Route as LessonsLevelIndexRouteImport } from './routes/lessons/$level/index'
import { Route as HobbiesHobbySlugIndexRouteImport } from './routes/hobbies/$hobbySlug/index'
import { Route as LessonsLevelUnitRouteImport } from './routes/lessons/$level/$unit'
import { Route as HobbiesHobbySlugQuizRouteImport } from './routes/hobbies/$hobbySlug/quiz'
import { Route as LessonsLevelUnitIndexRouteImport } from './routes/lessons/$level/$unit/index'
import { Route as LessonsLevelUnitLessonNumRouteImport } from './routes/lessons/$level/$unit/$lessonNum'
import { Route as LessonsLevelUnitLessonNumIndexRouteImport } from './routes/lessons/$level/$unit/$lessonNum/index'
import { Route as LessonsLevelUnitLessonNumQuizRouteImport } from './routes/lessons/$level/$unit/$lessonNum/quiz'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PhrasebookRoute = PhrasebookRouteImport.update({
  id: '/phrasebook',
  path: '/phrasebook',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbiesRoute = HobbiesRouteImport.update({
  id: '/hobbies',
  path: '/hobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbiesIndexRoute = HobbiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HobbiesRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileProgressRoute = ProfileProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ProfileRoute,
} as any)
const LessonsLevelRoute = LessonsLevelRouteImport.update({
  id: '/lessons/$level',
  path: '/lessons/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbiesHobbySlugRoute = HobbiesHobbySlugRouteImport.update({
  id: '/$hobbySlug',
  path: '/$hobbySlug',
  getParentRoute: () => HobbiesRoute,
} as any)
const LessonsLevelIndexRoute = LessonsLevelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonsLevelRoute,
} as any)
const HobbiesHobbySlugIndexRoute = HobbiesHobbySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HobbiesHobbySlugRoute,
} as any)
const LessonsLevelUnitRoute = LessonsLevelUnitRouteImport.update({
  id: '/$unit',
  path: '/$unit',
  getParentRoute: () => LessonsLevelRoute,
} as any)
const HobbiesHobbySlugQuizRoute = HobbiesHobbySlugQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => HobbiesHobbySlugRoute,
} as any)
const LessonsLevelUnitIndexRoute = LessonsLevelUnitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonsLevelUnitRoute,
} as any)
const LessonsLevelUnitLessonNumRoute =
  LessonsLevelUnitLessonNumRouteImport.update({
    id: '/$lessonNum',
    path: '/$lessonNum',
    getParentRoute: () => LessonsLevelUnitRoute,
  } as any)
const LessonsLevelUnitLessonNumIndexRoute =
  LessonsLevelUnitLessonNumIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LessonsLevelUnitLessonNumRoute,
  } as any)
const LessonsLevelUnitLessonNumQuizRoute =
  LessonsLevelUnitLessonNumQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => LessonsLevelUnitLessonNumRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/hobbies': typeof HobbiesRouteWithChildren
  '/phrasebook': typeof PhrasebookRoute
  '/profile': typeof ProfileRouteWithChildren
  '/hobbies/$hobbySlug': typeof HobbiesHobbySlugRouteWithChildren
  '/lessons/$level': typeof LessonsLevelRouteWithChildren
  '/profile/progress': typeof ProfileProgressRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/hobbies/': typeof HobbiesIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/hobbies/$hobbySlug/quiz': typeof HobbiesHobbySlugQuizRoute
  '/lessons/$level/$unit': typeof LessonsLevelUnitRouteWithChildren
  '/hobbies/$hobbySlug/': typeof HobbiesHobbySlugIndexRoute
  '/lessons/$level/': typeof LessonsLevelIndexRoute
  '/lessons/$level/$unit/$lessonNum': typeof LessonsLevelUnitLessonNumRouteWithChildren
  '/lessons/$level/$unit/': typeof LessonsLevelUnitIndexRoute
  '/lessons/$level/$unit/$lessonNum/quiz': typeof LessonsLevelUnitLessonNumQuizRoute
  '/lessons/$level/$unit/$lessonNum/': typeof LessonsLevelUnitLessonNumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/phrasebook': typeof PhrasebookRoute
  '/profile/progress': typeof ProfileProgressRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/hobbies': typeof HobbiesIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/hobbies/$hobbySlug/quiz': typeof HobbiesHobbySlugQuizRoute
  '/hobbies/$hobbySlug': typeof HobbiesHobbySlugIndexRoute
  '/lessons/$level': typeof LessonsLevelIndexRoute
  '/lessons/$level/$unit': typeof LessonsLevelUnitIndexRoute
  '/lessons/$level/$unit/$lessonNum/quiz': typeof LessonsLevelUnitLessonNumQuizRoute
  '/lessons/$level/$unit/$lessonNum': typeof LessonsLevelUnitLessonNumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/hobbies': typeof HobbiesRouteWithChildren
  '/phrasebook': typeof PhrasebookRoute
  '/profile': typeof ProfileRouteWithChildren
  '/hobbies/$hobbySlug': typeof HobbiesHobbySlugRouteWithChildren
  '/lessons/$level': typeof LessonsLevelRouteWithChildren
  '/profile/progress': typeof ProfileProgressRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/hobbies/': typeof HobbiesIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/hobbies/$hobbySlug/quiz': typeof HobbiesHobbySlugQuizRoute
  '/lessons/$level/$unit': typeof LessonsLevelUnitRouteWithChildren
  '/hobbies/$hobbySlug/': typeof HobbiesHobbySlugIndexRoute
  '/lessons/$level/': typeof LessonsLevelIndexRoute
  '/lessons/$level/$unit/$lessonNum': typeof LessonsLevelUnitLessonNumRouteWithChildren
  '/lessons/$level/$unit/': typeof LessonsLevelUnitIndexRoute
  '/lessons/$level/$unit/$lessonNum/quiz': typeof LessonsLevelUnitLessonNumQuizRoute
  '/lessons/$level/$unit/$lessonNum/': typeof LessonsLevelUnitLessonNumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dictionary'
    | '/hobbies'
    | '/phrasebook'
    | '/profile'
    | '/hobbies/$hobbySlug'
    | '/lessons/$level'
    | '/profile/progress'
    | '/profile/settings'
    | '/hobbies/'
    | '/lessons/'
    | '/profile/'
    | '/hobbies/$hobbySlug/quiz'
    | '/lessons/$level/$unit'
    | '/hobbies/$hobbySlug/'
    | '/lessons/$level/'
    | '/lessons/$level/$unit/$lessonNum'
    | '/lessons/$level/$unit/'
    | '/lessons/$level/$unit/$lessonNum/quiz'
    | '/lessons/$level/$unit/$lessonNum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dictionary'
    | '/phrasebook'
    | '/profile/progress'
    | '/profile/settings'
    | '/hobbies'
    | '/lessons'
    | '/profile'
    | '/hobbies/$hobbySlug/quiz'
    | '/hobbies/$hobbySlug'
    | '/lessons/$level'
    | '/lessons/$level/$unit'
    | '/lessons/$level/$unit/$lessonNum/quiz'
    | '/lessons/$level/$unit/$lessonNum'
  id:
    | '__root__'
    | '/'
    | '/dictionary'
    | '/hobbies'
    | '/phrasebook'
    | '/profile'
    | '/hobbies/$hobbySlug'
    | '/lessons/$level'
    | '/profile/progress'
    | '/profile/settings'
    | '/hobbies/'
    | '/lessons/'
    | '/profile/'
    | '/hobbies/$hobbySlug/quiz'
    | '/lessons/$level/$unit'
    | '/hobbies/$hobbySlug/'
    | '/lessons/$level/'
    | '/lessons/$level/$unit/$lessonNum'
    | '/lessons/$level/$unit/'
    | '/lessons/$level/$unit/$lessonNum/quiz'
    | '/lessons/$level/$unit/$lessonNum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DictionaryRoute: typeof DictionaryRoute
  HobbiesRoute: typeof HobbiesRouteWithChildren
  PhrasebookRoute: typeof PhrasebookRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  LessonsLevelRoute: typeof LessonsLevelRouteWithChildren
  LessonsIndexRoute: typeof LessonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrasebook': {
      id: '/phrasebook'
      path: '/phrasebook'
      fullPath: '/phrasebook'
      preLoaderRoute: typeof PhrasebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobbies': {
      id: '/hobbies'
      path: '/hobbies'
      fullPath: '/hobbies'
      preLoaderRoute: typeof HobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobbies/': {
      id: '/hobbies/'
      path: '/'
      fullPath: '/hobbies/'
      preLoaderRoute: typeof HobbiesIndexRouteImport
      parentRoute: typeof HobbiesRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/progress': {
      id: '/profile/progress'
      path: '/progress'
      fullPath: '/profile/progress'
      preLoaderRoute: typeof ProfileProgressRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/lessons/$level': {
      id: '/lessons/$level'
      path: '/lessons/$level'
      fullPath: '/lessons/$level'
      preLoaderRoute: typeof LessonsLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobbies/$hobbySlug': {
      id: '/hobbies/$hobbySlug'
      path: '/$hobbySlug'
      fullPath: '/hobbies/$hobbySlug'
      preLoaderRoute: typeof HobbiesHobbySlugRouteImport
      parentRoute: typeof HobbiesRoute
    }
    '/lessons/$level/': {
      id: '/lessons/$level/'
      path: '/'
      fullPath: '/lessons/$level/'
      preLoaderRoute: typeof LessonsLevelIndexRouteImport
      parentRoute: typeof LessonsLevelRoute
    }
    '/hobbies/$hobbySlug/': {
      id: '/hobbies/$hobbySlug/'
      path: '/'
      fullPath: '/hobbies/$hobbySlug/'
      preLoaderRoute: typeof HobbiesHobbySlugIndexRouteImport
      parentRoute: typeof HobbiesHobbySlugRoute
    }
    '/lessons/$level/$unit': {
      id: '/lessons/$level/$unit'
      path: '/$unit'
      fullPath: '/lessons/$level/$unit'
      preLoaderRoute: typeof LessonsLevelUnitRouteImport
      parentRoute: typeof LessonsLevelRoute
    }
    '/hobbies/$hobbySlug/quiz': {
      id: '/hobbies/$hobbySlug/quiz'
      path: '/quiz'
      fullPath: '/hobbies/$hobbySlug/quiz'
      preLoaderRoute: typeof HobbiesHobbySlugQuizRouteImport
      parentRoute: typeof HobbiesHobbySlugRoute
    }
    '/lessons/$level/$unit/': {
      id: '/lessons/$level/$unit/'
      path: '/'
      fullPath: '/lessons/$level/$unit/'
      preLoaderRoute: typeof LessonsLevelUnitIndexRouteImport
      parentRoute: typeof LessonsLevelUnitRoute
    }
    '/lessons/$level/$unit/$lessonNum': {
      id: '/lessons/$level/$unit/$lessonNum'
      path: '/$lessonNum'
      fullPath: '/lessons/$level/$unit/$lessonNum'
      preLoaderRoute: typeof LessonsLevelUnitLessonNumRouteImport
      parentRoute: typeof LessonsLevelUnitRoute
    }
    '/lessons/$level/$unit/$lessonNum/': {
      id: '/lessons/$level/$unit/$lessonNum/'
      path: '/'
      fullPath: '/lessons/$level/$unit/$lessonNum/'
      preLoaderRoute: typeof LessonsLevelUnitLessonNumIndexRouteImport
      parentRoute: typeof LessonsLevelUnitLessonNumRoute
    }
    '/lessons/$level/$unit/$lessonNum/quiz': {
      id: '/lessons/$level/$unit/$lessonNum/quiz'
      path: '/quiz'
      fullPath: '/lessons/$level/$unit/$lessonNum/quiz'
      preLoaderRoute: typeof LessonsLevelUnitLessonNumQuizRouteImport
      parentRoute: typeof LessonsLevelUnitLessonNumRoute
    }
  }
}

interface HobbiesHobbySlugRouteChildren {
  HobbiesHobbySlugQuizRoute: typeof HobbiesHobbySlugQuizRoute
  HobbiesHobbySlugIndexRoute: typeof HobbiesHobbySlugIndexRoute
}

const HobbiesHobbySlugRouteChildren: HobbiesHobbySlugRouteChildren = {
  HobbiesHobbySlugQuizRoute: HobbiesHobbySlugQuizRoute,
  HobbiesHobbySlugIndexRoute: HobbiesHobbySlugIndexRoute,
}

const HobbiesHobbySlugRouteWithChildren =
  HobbiesHobbySlugRoute._addFileChildren(HobbiesHobbySlugRouteChildren)

interface HobbiesRouteChildren {
  HobbiesHobbySlugRoute: typeof HobbiesHobbySlugRouteWithChildren
  HobbiesIndexRoute: typeof HobbiesIndexRoute
}

const HobbiesRouteChildren: HobbiesRouteChildren = {
  HobbiesHobbySlugRoute: HobbiesHobbySlugRouteWithChildren,
  HobbiesIndexRoute: HobbiesIndexRoute,
}

const HobbiesRouteWithChildren =
  HobbiesRoute._addFileChildren(HobbiesRouteChildren)

interface ProfileRouteChildren {
  ProfileProgressRoute: typeof ProfileProgressRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileProgressRoute: ProfileProgressRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface LessonsLevelUnitLessonNumRouteChildren {
  LessonsLevelUnitLessonNumQuizRoute: typeof LessonsLevelUnitLessonNumQuizRoute
  LessonsLevelUnitLessonNumIndexRoute: typeof LessonsLevelUnitLessonNumIndexRoute
}

const LessonsLevelUnitLessonNumRouteChildren: LessonsLevelUnitLessonNumRouteChildren =
  {
    LessonsLevelUnitLessonNumQuizRoute: LessonsLevelUnitLessonNumQuizRoute,
    LessonsLevelUnitLessonNumIndexRoute: LessonsLevelUnitLessonNumIndexRoute,
  }

const LessonsLevelUnitLessonNumRouteWithChildren =
  LessonsLevelUnitLessonNumRoute._addFileChildren(
    LessonsLevelUnitLessonNumRouteChildren,
  )

interface LessonsLevelUnitRouteChildren {
  LessonsLevelUnitLessonNumRoute: typeof LessonsLevelUnitLessonNumRouteWithChildren
  LessonsLevelUnitIndexRoute: typeof LessonsLevelUnitIndexRoute
}

const LessonsLevelUnitRouteChildren: LessonsLevelUnitRouteChildren = {
  LessonsLevelUnitLessonNumRoute: LessonsLevelUnitLessonNumRouteWithChildren,
  LessonsLevelUnitIndexRoute: LessonsLevelUnitIndexRoute,
}

const LessonsLevelUnitRouteWithChildren =
  LessonsLevelUnitRoute._addFileChildren(LessonsLevelUnitRouteChildren)

interface LessonsLevelRouteChildren {
  LessonsLevelUnitRoute: typeof LessonsLevelUnitRouteWithChildren
  LessonsLevelIndexRoute: typeof LessonsLevelIndexRoute
}

const LessonsLevelRouteChildren: LessonsLevelRouteChildren = {
  LessonsLevelUnitRoute: LessonsLevelUnitRouteWithChildren,
  LessonsLevelIndexRoute: LessonsLevelIndexRoute,
}

const LessonsLevelRouteWithChildren = LessonsLevelRoute._addFileChildren(
  LessonsLevelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DictionaryRoute: DictionaryRoute,
  HobbiesRoute: HobbiesRouteWithChildren,
  PhrasebookRoute: PhrasebookRoute,
  ProfileRoute: ProfileRouteWithChildren,
  LessonsLevelRoute: LessonsLevelRouteWithChildren,
  LessonsIndexRoute: LessonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
