/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PhrasebookRouteImport } from './routes/phrasebook'
import { Route as HobbiesRouteImport } from './routes/hobbies'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'
import { Route as LessonsIdIndexRouteImport } from './routes/lessons.$id.index'
import { Route as LessonsIdQuizRouteImport } from './routes/lessons.$id.quiz'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PhrasebookRoute = PhrasebookRouteImport.update({
  id: '/phrasebook',
  path: '/phrasebook',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbiesRoute = HobbiesRouteImport.update({
  id: '/hobbies',
  path: '/hobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdIndexRoute = LessonsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonsIdRoute,
} as any)
const LessonsIdQuizRoute = LessonsIdQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => LessonsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/hobbies': typeof HobbiesRoute
  '/phrasebook': typeof PhrasebookRoute
  '/profile': typeof ProfileRouteWithChildren
  '/lessons/$id': typeof LessonsIdRouteWithChildren
  '/profile/settings': typeof ProfileSettingsRoute
  '/lessons/': typeof LessonsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/lessons/$id/quiz': typeof LessonsIdQuizRoute
  '/lessons/$id/': typeof LessonsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/hobbies': typeof HobbiesRoute
  '/phrasebook': typeof PhrasebookRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/lessons': typeof LessonsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/lessons/$id/quiz': typeof LessonsIdQuizRoute
  '/lessons/$id': typeof LessonsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dictionary': typeof DictionaryRoute
  '/hobbies': typeof HobbiesRoute
  '/phrasebook': typeof PhrasebookRoute
  '/profile': typeof ProfileRouteWithChildren
  '/lessons/$id': typeof LessonsIdRouteWithChildren
  '/profile/settings': typeof ProfileSettingsRoute
  '/lessons/': typeof LessonsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/lessons/$id/quiz': typeof LessonsIdQuizRoute
  '/lessons/$id/': typeof LessonsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dictionary'
    | '/hobbies'
    | '/phrasebook'
    | '/profile'
    | '/lessons/$id'
    | '/profile/settings'
    | '/lessons/'
    | '/profile/'
    | '/lessons/$id/quiz'
    | '/lessons/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dictionary'
    | '/hobbies'
    | '/phrasebook'
    | '/profile/settings'
    | '/lessons'
    | '/profile'
    | '/lessons/$id/quiz'
    | '/lessons/$id'
  id:
    | '__root__'
    | '/'
    | '/dictionary'
    | '/hobbies'
    | '/phrasebook'
    | '/profile'
    | '/lessons/$id'
    | '/profile/settings'
    | '/lessons/'
    | '/profile/'
    | '/lessons/$id/quiz'
    | '/lessons/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DictionaryRoute: typeof DictionaryRoute
  HobbiesRoute: typeof HobbiesRoute
  PhrasebookRoute: typeof PhrasebookRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  LessonsIdRoute: typeof LessonsIdRouteWithChildren
  LessonsIndexRoute: typeof LessonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrasebook': {
      id: '/phrasebook'
      path: '/phrasebook'
      fullPath: '/phrasebook'
      preLoaderRoute: typeof PhrasebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobbies': {
      id: '/hobbies'
      path: '/hobbies'
      fullPath: '/hobbies'
      preLoaderRoute: typeof HobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id/': {
      id: '/lessons/$id/'
      path: '/'
      fullPath: '/lessons/$id/'
      preLoaderRoute: typeof LessonsIdIndexRouteImport
      parentRoute: typeof LessonsIdRoute
    }
    '/lessons/$id/quiz': {
      id: '/lessons/$id/quiz'
      path: '/quiz'
      fullPath: '/lessons/$id/quiz'
      preLoaderRoute: typeof LessonsIdQuizRouteImport
      parentRoute: typeof LessonsIdRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface LessonsIdRouteChildren {
  LessonsIdQuizRoute: typeof LessonsIdQuizRoute
  LessonsIdIndexRoute: typeof LessonsIdIndexRoute
}

const LessonsIdRouteChildren: LessonsIdRouteChildren = {
  LessonsIdQuizRoute: LessonsIdQuizRoute,
  LessonsIdIndexRoute: LessonsIdIndexRoute,
}

const LessonsIdRouteWithChildren = LessonsIdRoute._addFileChildren(
  LessonsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DictionaryRoute: DictionaryRoute,
  HobbiesRoute: HobbiesRoute,
  PhrasebookRoute: PhrasebookRoute,
  ProfileRoute: ProfileRouteWithChildren,
  LessonsIdRoute: LessonsIdRouteWithChildren,
  LessonsIndexRoute: LessonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
